services:
  cert-generator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ./certs:/certs
      - ./generate-certs.sh:/generate-certs.sh 
    command: bash -c "chmod +x /generate-certs.sh && /generate-certs.sh"

  aichatintegration.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - CHATCLIENTCONFIG__MODELNAME=llama3.2 #this should match the model you are running
      - CHATCLIENTCONFIG__URI=http://host.docker.internal:11434/
    ports:
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./certs:/https
    depends_on:
      - cert-generator

  aichatintegration.client:
    build:
      context: ./aichatintegration.client
      dockerfile: Dockerfile
    volumes:
      - ./aichatintegration.client:/app
      - /app/node_modules
      - ./certs:/app/certs
    ports:
      - "7040:7040"
    environment:
      - VITE_API_BASE_URL=https://localhost:5001
      - CERT_PATH=/app/certs
    depends_on:
      - cert-generator
      - aichatintegration.server
